export const endpoints = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    google: '/auth/google',
    refresh: '/auth/refresh',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    verifyEmail: '/auth/verify-email',
    me: '/auth/me',
    updateMe: '/auth/me',
    logout: '/auth/logout',
  },
  vehicles: '/vehicles',
  vehicleChecks: (vehicleId: string) => `/vehicles/${vehicleId}/checks`,
  checks: '/checks',
  checkLogs: (checkId: string) => `/checks/${checkId}/logs`,
  checkReminder: (checkId: string) => `/checks/${checkId}/reminder`,
  trips: '/trips',
  trip: (id: string) => `/trips/${id}`,
  deals: '/deals',
  branches: '/branches',
  products: '/products',
  notificationPreferences: '/profile/notifications',
  notificationPreference: (key: string) => `/profile/notifications/${key}`,
} as const;
